### ISSUE TITLE
Magma 1.12 - Crash on Worlds Loading

### ISSUE THREAD

**Issue by Switch-Back18** [magmamaintained/Magma-1.12.2#6]
**Minecraft Version:** 1.12

**Forge Version:** 14.23.5.2860 // Magma 4c00eba

**Logs:** crash report : https://mclo.gs/60DgsOp // logs : https://mclo.gs/bF2HyWW

**Steps to Reproduce:**
 1. Install my pack  (https://legacy.curseforge.com/minecraft/modpacks/munchies-origin)
 2. Launch Magma
 3. When worlds start loading the server crash

**Comment by TonimatasDEV** [comment]
Many mods and the error are very generic. When I have time I will try to fix it.

**Comment by Switch-Back18** [comment]
I found the mod that causes the crash 

It's Alfheim Lightning Engine 

https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/5229610

Without it, the server start

**Comment by TonimatasDEV** [comment]
Thanks you very much for the information. I will try to fix it as soon as I have time

**Comment by TonimatasDEV** [comment]
@MathisSkate Fixed in the b4c01d2. When CI finish it will be pushed to downlaod
