### ISSUE TITLE
New Magma Update Crashes RLCraft Server

### ISSUE THREAD

**Issue by MrLewie** [magmamaintained/Magma-1.12.2#8]
**Minecraft Version:** {1.12.2}

**Forge Version:** {1.12.2 - 14.23.5.2859}

**Logs:** crash report: https://gist.github.com/MrLewie/4bf9a08145810ade0424aa8578f14331
latest.log: https://gist.githubusercontent.com/MrLewie/f11afa14119896054cf729582832bab8/raw/7a1155f5162690af693823f6ff7c3152746366ea/gistfile1.txt

Sorry if this is in an incorrect format; I have basically zero knowledge about hosting a server, and my friend helped me set things up. The server crashes on startup, and crashed initially after Magma updated with zero errors on shutdown. I'm using the RLCraft modpack, and my friend believes it is a chunk loading error that is causing the server to crash.

Please let me know if there is anything I should do differently with the format of this issue report, or if there is anything that I can do for the server.

Thank you for your help,
MrLewie.

**Comment by TonimatasDEV** [comment]
@MrLewie I can't access to the logs

**Comment by MrLewie** [comment]
@TonimatasDEV https://gist.github.com/MrLewie/4bf9a08145810ade0424aa8578f14331 and https://gist.githubusercontent.com/MrLewie/f11afa14119896054cf729582832bab8/raw/7a1155f5162690af693823f6ff7c3152746366ea/gistfile1.txt 

I think the bracket messed up the link sorry!

**Comment by TonimatasDEV** [comment]
@MrLewie It's a problem with EssentialsX
